### PR TITLE
fixed elrepo install for centos stream 9

### PR DESCRIPTION
**Pull request by g0rgamesh**

### CODE REVIEW

**Review by mnasiadka — CHANGES_REQUESTED** [review]
ELRepo is for EL9 (RHEL9, Rocky Linux 9, Alma Linux 9, and so on), CentOS Stream KMODs SIG is for Stream - we shouldn't be using this for Stream 9 (it will work sometimes, but not always, due to kernel images not being in sync between EL9 and EL9s).

**Comment by g0rgamesh** [comment]
> ELRepo is for EL9 (RHEL9, Rocky Linux 9, Alma Linux 9, and so on), CentOS Stream KMODs SIG is for Stream - we shouldn't be using this for Stream 9 (it will work sometimes, but not always, due to kernel images not being in sync between EL9 and EL9s).

that makes sense, but shouldn't we at least give that option to people who want to try it?

**Comment by mnasiadka** [comment]
> > ELRepo is for EL9 (RHEL9, Rocky Linux 9, Alma Linux 9, and so on), CentOS Stream KMODs SIG is for Stream - we shouldn't be using this for Stream 9 (it will work sometimes, but not always, due to kernel images not being in sync between EL9 and EL9s).
> 
> that makes sense, but shouldn't we at least give that option to people who want to try it?

You want to build two versions of images? One with ELRepo, second with KMODs SIG repos?
I'm pretty sure ELRepo usage will break Stream image builds at some point(s), like it did in the past - so we're rather inflicting self-damage with that one.

**Comment by g0rgamesh** [comment]
> > > ELRepo is for EL9 (RHEL9, Rocky Linux 9, Alma Linux 9, and so on), CentOS Stream KMODs SIG is for Stream - we shouldn't be using this for Stream 9 (it will work sometimes, but not always, due to kernel images not being in sync between EL9 and EL9s).
> > 
> > 
> > that makes sense, but shouldn't we at least give that option to people who want to try it?
> 
> You want to build two versions of images? One with ELRepo, second with KMODs SIG repos? I'm pretty sure ELRepo usage will break Stream image builds at some point(s), like it did in the past - so we're rather inflicting self-damage with that one.

No, I was thinking for anyone who would need some packages from there.

**Pull request closed without merging**
